spb_rest:
    resource: "@SpbRestBundle/Resources/config/routing.yml"
    type:     annotation
    prefix:   /

spb_rexchange:
    resource: "@SpbRexchangeBundle/Resources/config/routing.yml"
    prefix:   /

