spb_rest:
    resource: "@SpbRestBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type: rest
    resource: Spb\RestBundle\Controller\UsersController

spb_rexchange:
    resource: "@SpbRexchangeBundle/Resources/config/routing.yml"
    prefix:   /

